const products = [
  {
    itemName: 'Atta - Whole wheat 1Kg Pouch',
    unitPrice: 57,
    unit: '1PC',
    brandName: 'Aashirvaad',
    discountedPrice: 0,
    imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/126906_6-aashirvaad-atta-whole-wheat.jpg',
    itemId: 123,
  },
  {
    itemName: 'Maida',
    unitPrice: 24,
    unit: '500gm',
    brandName: 'Bhagyalaxmi',
    discountedPrice: 0,
    imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/40044729_4-bb-royal-maida.jpg',
    itemId: 122,
  },
  {
    itemName: 'Gram flour',
    unitPrice: 48,
    unit: '500gm',
    brandName: 'Bhagyalaxmi',
    discountedPrice: 0,
    imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/40014292_1-phalada-pure-sure-organic-gram-flour-besan.jpg',
    itemId: 124,
  },
  {
    itemName: 'Rice flour',
    unitPrice: 24,
    unit: '500gm',
    brandName: 'Bhagyalaxmi',
    discountedPrice: 0,
    imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/40144597_3-safe-harvest-rice-flour-pesticide-free.jpg',
    itemId: 125,
  },
  {
    itemName: 'Atta whole wheat 1kg',
    unitPrice: 64,
    unit: '1kg',
    brandName: 'Bhagyalaxmi',
    discountedPrice: 0,
    imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/40006928_7-safe-harvest-whole-wheat-atta-pesticide-free.jpg',
    itemId: 127,
  },
  {
    itemName: 'Atta multigrain',
    unitPrice: 62,
    unit: '1kg',
    brandName: 'Aashirvaad',
    discountedPrice: 0,
    imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/284420_7-aashirvaad-multigrains-atta.jpg',
    itemId: 128,
  },
];

export default products;